# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-msk-apache-kafka-cluster
  description: Terraform module to provision AWS MSK
  homepage: https://cloudposse.com/accelerate
  topics: ""
