name: lint

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  lint-readme:
    name: readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cloudposse/build-harness@0.44.1
        with:
          entrypoint: /usr/bin/make
          args: readme/lint

  super-linter:
    name: superlinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TERRAFORM_TERRASCAN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
